require('plugins')

require('config.devicons')
require('config.telescope')
require('config.compe')
require('config.floaterm')
require('config.indent-blankline')
require('config.sayonara')
require('config.lsp')
require('config.neogit')
require('config.treesitter')
require('config.lightbulb')
require('config.tokyonight')
require('config.lualine')
require('config.whichkey')

require('settings')
require('maps')
require('autocmds')
