require('plugins')
require('settings')
require('maps')
require('autocmds')

require('config.telescope')
require('config.compe')
require('config.floaterm')
require('config.indent-blankline')
require('config.sayonara')
require('config.lsp')
require('config.galaxyline')
require('config.neogit')
require('config.treesitter')
require('config.lightbulb')
