k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: true
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: true
    textWrap: false
    showTime: false
  currentContext: teleport.atlasoffice.io-6abf56c8-adec-4434-be4d-3f83c98b5eab
  currentCluster: teleport.atlasoffice.io
  clusters:
    arn:aws:eks:us-west-2:602864681186:cluster/atlas:
      namespace:
        active: ""
        favorites:
        - all
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    teleport.atlasoffice.io:
      namespace:
        active: ""
        favorites:
        - all
        - default
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
