k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: true
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: true
    textWrap: false
    showTime: false
  currentContext: teleport.atlassandbox.io-00000000-0000-0000-0000-000000000003
  currentCluster: teleport.atlassandbox.io
  clusters:
    teleport.atlassandbox.io:
      namespace:
        active: ""
        favorites:
        - all
        - default
      view:
        active: deployment
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
