k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: true
  logoless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: true
    textWrap: false
    showTime: false
  currentContext: teleport.atlaslive.io-2673bfe7-ecc5-4839-9c21-5fb2a29cab33
  currentCluster: teleport.atlaslive.io
  clusters:
    teleport.atlaslive.io:
      namespace:
        active: all
        favorites:
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/8q/wbr57phn0179dqp0k5glmdrr0000gn/T/k9s-screens-joshsymonds
